version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      -"5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  app:
    image: thulasiramtejavegi/user_email-app:latest
    ports:
      - "5001:5001"
    depends_on:
      - postgres:
          condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=userdb
      - DB_USER=posrgres
      - DB_PASSWORD=posrgres
volumes:
  postgres_data: